/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package financeiro.gui;

import financeiro.model.PedidoBobina;
import financeiro.DAO.PedidoBobinaDao;
import financeiro.conexao.Conexao;
import financeiro.model.PedidoBobina;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author Ledilson
 */
public class CadastroPedidoBobina extends javax.swing.JInternalFrame {

    //Conversão de data
    private final SimpleDateFormat sdfPedido = new SimpleDateFormat("dd-MM-yyyy");
    private final SimpleDateFormat sdfEntrega = new SimpleDateFormat("dd-MM-yyyy");

    /**
     * Creates new form CadastroPedidoBobina
     */
    public CadastroPedidoBobina() {
        initComponents();

        carregaTabela();
        desativaBotoes();
        desativaCampos();

        CentralizarJTextFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAlterar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPedido = new javax.swing.JTable();
        txtNomeEmpresa = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtChequeA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtChequeB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtChequeC = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbTotalBobina = new javax.swing.JLabel();
        lblTotalValor = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbxPag = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtDataPedido = new javax.swing.JFormattedTextField();
        txtDataEntrega = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Cadastro de Pedidos Entregues ");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tbPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data hora", "Empresa", "Valor", "Qtd", "Data Pedido", "Data Entrega", "N. Cheque 1", "N. Cheque 2", "N. Cheque 3", "Forma Pag.", "Obs"
            }
        ));
        tbPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPedido);

        txtNomeEmpresa.setNextFocusableComponent(txtValor);

        txtValor.setNextFocusableComponent(txtDataPedido);

        jLabel1.setText("Empresa.:");

        jLabel2.setText("Quant.:");

        jLabel3.setText("Valor.:");

        txtQuant.setNextFocusableComponent(txtDataEntrega);

        jLabel4.setText("Data Pedido.:");

        jLabel5.setText("Data Entrega.:");

        jLabel6.setText("N.Cheque 1.:");

        txtChequeA.setNextFocusableComponent(txtChequeB);

        jLabel7.setText("N.Cheque 2.:");

        txtChequeB.setNextFocusableComponent(txtChequeC);

        jLabel8.setText("N.Cheque 3.:");

        txtChequeC.setNextFocusableComponent(txtQuant);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText(" T. Geral  ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText(" T. Bobinas ");

        lbTotalBobina.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTotalBobina.setText("0");

        lblTotalValor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotalValor.setText("0.00");

        jLabel11.setText("Forma Pag.:");

        cbxPag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Boleto", "Cart.Débito", "Cart.Crédito", "Conta Salário", "Ch à vista", "Ch 30d", "Ch 60d", "Ch 90d", "Dinheiro", "Pag. Pendente", "PIX", "Transf. Bancária" }));

        jLabel12.setText("Obs.:");

        txtObs.setText(" ");
        txtObs.setNextFocusableComponent(btGravar);

        try {
            txtDataPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataEntrega))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(11, 11, 11)
                                        .addComponent(txtNomeEmpresa)))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel11)
                                        .addGap(3, 3, 3)
                                        .addComponent(cbxPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtChequeB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtChequeC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtChequeA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(lbTotalBobina, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(127, 127, 127))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTotalValor)
                                        .addGap(137, 137, 137))))))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btNovo)
                            .addComponent(btGravar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAlterar)
                                    .addComponent(btExcluir))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalValor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTotalBobina)))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtChequeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtChequeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtChequeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tbPedido.getModel();

        //Defini o tamanho da tabela
        tbPedido.getColumnModel().getColumn(0).setPreferredWidth(120);
        tbPedido.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbPedido.getColumnModel().getColumn(2).setPreferredWidth(80);
        tbPedido.getColumnModel().getColumn(3).setPreferredWidth(80);
        tbPedido.getColumnModel().getColumn(4).setPreferredWidth(80);
        tbPedido.getColumnModel().getColumn(5).setPreferredWidth(60);
        tbPedido.getColumnModel().getColumn(6).setPreferredWidth(50);
        tbPedido.getColumnModel().getColumn(7).setPreferredWidth(50);
        tbPedido.getColumnModel().getColumn(8).setPreferredWidth(60);
        tbPedido.getColumnModel().getColumn(9).setPreferredWidth(60);
        tbPedido.getColumnModel().getColumn(10).setPreferredWidth(60);

        // Criar um renderizador centralizado
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Aplicar o renderizador às colunas de valorpedido (índice 1) e quantidadebobina (índice 2)
        //   tbPedido.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        //  tbPedido.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tbPedido.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tbPedido.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tbPedido.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        tbPedido.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        tbPedido.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
        tbPedido.getColumnModel().getColumn(7).setCellRenderer(centerRenderer);
        //tbPedido.getColumnModel().getColumn(8).setCellRenderer(centerRenderer);
        //  tbPedido.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);
//        tbPedido.getColumnModel().getColumn(10).setCellRenderer(centerRenderer);
        try {
            Connection con = Conexao.getConnection();
            PreparedStatement pstm;
            ResultSet rs;

            String sqlSomaTotalBobinas = "SELECT SUM(quantidadeBobina) AS totalBobinas FROM pedidobobina WHERE EXTRACT(MONTH FROM CAST(dataPedido AS DATE)) = ? AND EXTRACT(YEAR FROM CAST(dataPedido AS DATE)) = ?";

            // Obtém o mês e o ano atuais
            Calendar cal = Calendar.getInstance();
            int mesAtual = -1;
            int mesAtualNovo = cal.get(Calendar.MONTH) + 1; // Note que os meses em Java começam do zero
            int anoAtual = cal.get(Calendar.YEAR);

            //verificar se o mês atual
            if (mesAtual != mesAtualNovo) {
                lbTotalBobina.setText("0");
                lblTotalValor.setText("0");
                modelo.setNumRows(0);

                //atualiza o mês atual
                mesAtual = mesAtualNovo;
            }
            try (PreparedStatement statementBobinas = con.prepareStatement(sqlSomaTotalBobinas)) {
                statementBobinas.setInt(1, mesAtual);
                statementBobinas.setInt(2, anoAtual);

                try (ResultSet resultadoBobinas = statementBobinas.executeQuery()) {
                    if (resultadoBobinas.next()) {
                        int totalBobinas = resultadoBobinas.getInt("totalBobinas");
                        lbTotalBobina.setText(String.valueOf(totalBobinas));
                    } else {
                        // Se não houver resultados, define o total como zero
                        lbTotalBobina.setText("0");
                    }
                }
            } catch (SQLException e) {
                // Trate exceções SQL conforme necessário
                e.printStackTrace();
            }
            // Consulta para obter a soma total da coluna Valor Pedido para o mês atual
            String sqlSomaTotalReal = "SELECT SUM(valorpedido) AS totalValor FROM pedidobobina WHERE EXTRACT(MONTH FROM CAST(dataPedido AS DATE)) = ? AND EXTRACT(YEAR FROM CAST(dataPedido AS DATE)) = ?";

            try (PreparedStatement statementValor = con.prepareStatement(sqlSomaTotalReal)) {
                statementValor.setInt(1, mesAtual);
                statementValor.setInt(2, anoAtual);

                try (ResultSet resultadoValor = statementValor.executeQuery()) {
                    if (resultadoValor.next()) {

                        Double totalValor = resultadoValor.getDouble("totalValor");

                        //Formatar o valor
                        DecimalFormat decimalFormat = new DecimalFormat("#.##");
                        String valorFormatado = decimalFormat.format(totalValor);

                        lblTotalValor.setText(String.valueOf(valorFormatado));
                    } else {
                        // Se não houver resultados, define o total como zero
                        lblTotalValor.setText("0");
                    }
                }
            } catch (SQLException e) {
                // Trate exceções SQL conforme necessário
                e.printStackTrace();
            }
            // Limpa a tabela antes de preencher os novos dados
            modelo.setNumRows(0);
            pstm = con.prepareStatement("SELECT id,datahora,nomecliente,valorpedido,quantidadebobina,datapedido,dataentrega,numerochequea,numerochequeb,numerochequec,pagpedido,observacao FROM pedidobobina ORDER BY  id DESC;");
            rs = pstm.executeQuery();
            //Formatar o valor no campo jtable
            NumberFormat currencyValor = NumberFormat.getCurrencyInstance();
            while (rs.next()) {

                modelo.addRow(new Object[]{
                    rs.getString("datahora"),
                    rs.getString("nomecliente"),
                    currencyValor.format(rs.getDouble("valorpedido")),
                    rs.getString("quantidadebobina"),
                    rs.getString("datapedido"),
                    rs.getString("dataentrega"),
                    rs.getString("numerochequea"),
                    rs.getString("numerochequeb"),
                    rs.getString("numerochequec"),
                    rs.getString("pagpedido"),
                    rs.getString("observacao"),});
            }
            Conexao.closeConnection(con, pstm, rs);
        } catch (Exception ErroSql) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar a tabela de dados: " + ErroSql, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void CentralizarJTextFields() {

        txtNomeEmpresa.setHorizontalAlignment(SwingConstants.CENTER);
        lbTotalBobina.setHorizontalAlignment(SwingConstants.CENTER);
        lblTotalValor.setHorizontalAlignment(SwingConstants.CENTER);
        txtValor.setHorizontalAlignment(SwingConstants.CENTER);
        txtDataEntrega.setHorizontalAlignment(SwingConstants.CENTER);
        txtDataPedido.setHorizontalAlignment(SwingConstants.CENTER);
        txtQuant.setHorizontalAlignment(SwingConstants.CENTER);
        txtChequeA.setHorizontalAlignment(SwingConstants.CENTER);
        txtChequeB.setHorizontalAlignment(SwingConstants.CENTER);
        txtChequeC.setHorizontalAlignment(SwingConstants.CENTER);
        //cbxPag.setHorizontalAlignment(SwingConstants.CENTER);
        txtObs.setHorizontalAlignment(SwingConstants.CENTER);
    }

    private void limparTexto() {
        txtNomeEmpresa.setText("");
        txtQuant.setText("");
        txtValor.setText("");
        txtDataEntrega.setText("");
        txtDataPedido.setText("");
        txtChequeA.setText("");
        txtChequeB.setText("");
        txtChequeC.setText("");
        txtObs.setText("");

        // Limpar JComboBox (usando setSelectedItem(null))
        cbxPag.setSelectedItem(null);

        btGravar.setEnabled(false);
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
    }

    private void desativaBotoes() {
        btGravar.setEnabled(false);
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
    }

    private void desativaCampos() {
        txtNomeEmpresa.setEnabled(false);
        txtValor.setEnabled(false);
        txtQuant.setEnabled(false);
        txtDataEntrega.setEnabled(false);
        txtDataPedido.setEnabled(false);
        txtChequeA.setEnabled(false);
        txtChequeB.setEnabled(false);
        txtChequeC.setEnabled(false);
        txtObs.setEnabled(false);
        cbxPag.setEnabled(false);
    }

    private void ativaBotoes() {
        btGravar.setEnabled(true);
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
    }

    private void ativaCampos() {
        txtNomeEmpresa.setEnabled(true);
        txtValor.setEnabled(true);
        txtQuant.setEnabled(true);
        txtDataEntrega.setEnabled(true);
        txtDataPedido.setEnabled(true);
        txtChequeA.setEnabled(true);
        txtChequeB.setEnabled(true);
        txtChequeC.setEnabled(true);
        txtObs.setEnabled(true);
        cbxPag.setEnabled(true);
    }
    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed

        PedidoBobina l = new PedidoBobina();
        PedidoBobinaDao dao = new PedidoBobinaDao();

        int index = tbPedido.getSelectedRow();
        l = dao.listarPedidoBobina().get(index);

        switch (JOptionPane.showConfirmDialog(null,
                "[--ALTERAÇÃO DE DADOS--] \n Dado Atual"
                + "\n Empresa:  " + l.getNomeClientePedido()
                + "\n R$: " + l.getValorPedido()
                + "\n Quant : " + l.getQuantidadeBobina()
                + "\n Data Pedido: " + l.getDataPedido()
                + "\n Data Entrega: " + l.getDataEntrega()
                + "\n N. Cheque 1: " + l.getNumeroChequeA()
                + "\n N. Cheque 2: " + l.getNumeroChequeB()
                + "\n N. Cheque 3: " + l.getNumeroChequeC()
                + "\n Forma Pag.: " + l.getPagPedido()
                + "\n Obs.: " + l.getObservacaoPagamento()
                + "\n Será alterado \n Empresa: "
                + txtNomeEmpresa.getText()
                + "\n R$: " + txtValor.getText()
                + "\n Quant : " + txtQuant.getText()
                + "\n Data Pedido: " + txtDataPedido.getText()
                + "\n Data Entrega: " + txtDataEntrega.getText()
                + "\n N. Cheque 1: " + txtChequeA.getText()
                + "\n  N. Cheque 2: " + txtChequeB.getText()
                + "\n  N. Cheque 3: " + txtChequeC.getText()
                + "\n Forma Pag.: " + cbxPag.getSelectedItem()
                + "\n Obs.: " + txtObs.getText()
                + "\n Deseja realmente fazer alteração?",
                "Alteração de dados.", JOptionPane.YES_NO_OPTION)) {

            case 0:

                l.setNomeClientePedido(txtNomeEmpresa.getText());
                l.setValorPedido(Double.parseDouble(txtValor.getText()));
                l.setQuantidadeBobina(Integer.parseInt(txtQuant.getText()));

                l.setNumeroChequeA(txtChequeA.getText());
                l.setNumeroChequeB(txtChequeB.getText());
                l.setNumeroChequeC(txtChequeC.getText());

                l.setPagPedido((String) cbxPag.getSelectedItem());
                l.setObservacaoPagamento(txtObs.getText());

                // Entrada da Data cliente
                try {
                    java.util.Date dataFormatada = sdfPedido.parse(txtDataPedido.getText());
                    java.sql.Date dataSQL = new java.sql.Date(dataFormatada.getTime());
                    l.setDataPedido(dataSQL);
                } catch (ParseException ex) {
                    // Logger.getLogger(CadastroBoleto.class.getName()).log(Level.SEVERE, null, ex);

                    JOptionPane.showMessageDialog(null, "Formato de data incorreto. Por favor, insira a data no formato correto (dd-MM-yyyy).", "Erro", JOptionPane.ERROR_MESSAGE);
                }
                // Entrada da Data Empresa
                try {
                    java.util.Date dataFormatada = sdfEntrega.parse(txtDataEntrega.getText());

                    java.sql.Date dataSQL = new java.sql.Date(dataFormatada.getTime());

                    l.setDataEntrega(dataSQL);

                } catch (ParseException ex) {

                    // Logger.getLogger(CadastroBoleto.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Formato de data incorreto. Por favor, insira a data no formato correto (dd-MM-yyyy).", "Erro", JOptionPane.ERROR_MESSAGE);
                }

                dao.alterar(l);// faz alteração no banco de dados

                carregaTabela();
                limparTexto();
                desativaBotoes();
                desativaCampos();
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "Nenhuma alteração foi feita.",
                        "AVISO", JOptionPane.INFORMATION_MESSAGE);
                break;
        }

    }//GEN-LAST:event_btAlterarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        txtNomeEmpresa.setText("");
        limparTexto();
        ativaBotoes();
        ativaCampos();
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        if (txtNomeEmpresa.getText().isEmpty() || txtQuant.getText().isEmpty()
                || txtChequeA.getText().isEmpty() || txtChequeB.getText().isEmpty()
                || txtChequeC.getText().isEmpty() || cbxPag.getSelectedItem() == null
                || txtValor.getText().isEmpty()
                || txtDataPedido.getText().isEmpty() || txtDataEntrega.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de prosseguir.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PedidoBobina l = new PedidoBobina();
        PedidoBobinaDao dao = new PedidoBobinaDao();

        l.setNomeClientePedido(txtNomeEmpresa.getText());

        l.setValorPedido(Double.parseDouble(txtValor.getText()));

        //Converter integer para int
        l.setQuantidadeBobina(Integer.parseInt(txtQuant.getText()));

        l.setNumeroChequeA(txtChequeA.getText());
        l.setNumeroChequeB(txtChequeB.getText());
        l.setNumeroChequeC(txtChequeC.getText());

        l.setPagPedido((String) cbxPag.getSelectedItem());
        l.setObservacaoPagamento(txtObs.getText());

        // Entrada da Data cliente
        try {
            java.util.Date dataFormatada = sdfPedido.parse(txtDataPedido.getText());
            java.sql.Date dataSQL = new java.sql.Date(dataFormatada.getTime());
            l.setDataPedido(dataSQL);
        } catch (ParseException ex) {
            // Logger.getLogger(CadastroBoleto.class.getName()).log(Level.SEVERE, null, ex);

            JOptionPane.showMessageDialog(null, "Formato de data incorreto. Por favor, insira a data no formato correto (dd-MM-yyyy).", "Erro", JOptionPane.ERROR_MESSAGE);
            return; // Impede a continuação do método se a data estiver incorreta
        }
        // Entrada da Data Empresa
        try {
            java.util.Date dataFormatada = sdfEntrega.parse(txtDataEntrega.getText());

            java.sql.Date dataSQL = new java.sql.Date(dataFormatada.getTime());

            l.setDataEntrega(dataSQL);

        } catch (ParseException ex) {

            // Logger.getLogger(CadastroBoleto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Formato de data incorreto. Por favor, insira a data no formato correto (dd-MM-yyyy).", "Erro", JOptionPane.ERROR_MESSAGE);
            return; // Impede a continuação do método se a data estiver incorreta

        }
        // Exibir mensagem de sucesso

        dao.adicionar(l);
        // Carregando a tabela
        carregaTabela();
        //desativar campos 
        desativaCampos();
        // Limpar os campos, se necessário
        limparTexto();


    }//GEN-LAST:event_btGravarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

        PedidoBobina l = new PedidoBobina();
        PedidoBobinaDao dao = new PedidoBobinaDao();

        int index = tbPedido.getSelectedRow();

        l = dao.listarPedidoBobina().get(index);

        l.setNomeClientePedido(txtNomeEmpresa.getText());

        //Converter integer para int
        l.setQuantidadeBobina(Integer.parseInt(txtQuant.getText()));

        l.setNumeroChequeA(txtChequeA.getText());
        l.setNumeroChequeB(txtChequeB.getText());
        l.setNumeroChequeC(txtChequeC.getText());

        l.setPagPedido((String) cbxPag.getSelectedItem());
        l.setObservacaoPagamento(txtObs.getText());

        //Converte o valor
        String txtValorPedido = txtValor.getText();
        // Convertendo a String para double
        double valorPedido = Double.parseDouble(txtValorPedido);
        // Definindo o valor convertido na propriedade
        l.setValorPedido(valorPedido);

        switch (JOptionPane.showConfirmDialog(null, "Deseja excluir o Produto ? \n "
                + "\n Empresa:  " + l.getNomeClientePedido()
                + "\n R$: " + l.getValorPedido()
                + "\n Quant : " + l.getQuantidadeBobina()
                + "\n Data Pedido: " + l.getDataPedido()
                + "\n Data Entrega: " + l.getDataEntrega()
                + "\n N. Cheque 1: " + l.getNumeroChequeA()
                + "\n N. Cheque 2: " + l.getNumeroChequeB()
                + "\n N. Cheque 3: " + l.getNumeroChequeC()
                + "\n Pag.: " + l.getPagPedido()
                + "\n Obs.:" + l.getObservacaoPagamento(), "Confirmação ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)) {

            case 0:
                dao.remover(l);
                carregaTabela();
                limparTexto();
                desativaBotoes();
                desativaCampos();
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "Nehuma exclusão foi feita.", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                break;
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void tbPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPedidoMouseClicked
        // TODO add your handling code here:

        //Setando campos de texto com registros
        PedidoBobina g = new PedidoBobina();
        PedidoBobinaDao dao = new PedidoBobinaDao();

        int index = tbPedido.getSelectedRow();
        g = dao.listarPedidoBobina().get(index);

        txtNomeEmpresa.setText(g.getNomeClientePedido());

        // Setando valores nos campos de texto
        txtValor.setText(Double.toString(g.getValorPedido()));

        txtQuant.setText(String.valueOf(g.getQuantidadeBobina()));

        txtChequeA.setText(g.getNumeroChequeA());
        txtChequeB.setText(g.getNumeroChequeB());
        txtChequeC.setText(g.getNumeroChequeC());

        cbxPag.setSelectedItem(g.getPagPedido());
        txtObs.setText(g.getObservacaoPagamento());

        //  FORMATANDO A DATA
        //SimpleDateFormat sdfPedido = new SimpleDateFormat("dd-MM-yyyy");
        //txtDataPedido.setText(sdfPedido.format(g.getDataPedido()));
        JFormattedTextField txtDataPedido = new JFormattedTextField(new DefaultFormatterFactory(new DateFormatter(sdfPedido)));
        txtDataPedido.setValue(g.getDataPedido());

        //SimpleDateFormat sdfEntrega = new SimpleDateFormat("dd-MM-yyyy");
        // txtDataEntrega.setText(sdfEntrega.format(g.getDataEntrega()));
        SimpleDateFormat sdfEntrega = new SimpleDateFormat("dd-MM-yyyy");
        JFormattedTextField txtDataEntrega = new JFormattedTextField(new DefaultFormatterFactory(new DateFormatter(sdfEntrega)));
        txtDataEntrega.setValue(g.getDataEntrega());

        txtNomeEmpresa.setEnabled(true);

        txtValor.setEnabled(true);

        txtQuant.setEnabled(true);

        txtDataEntrega.setEnabled(true);
        txtDataPedido.setEnabled(true);

        txtChequeA.setEnabled(true);
        txtChequeB.setEnabled(true);
        txtChequeC.setEnabled(true);

        cbxPag.setEnabled(true);
        txtObs.setEnabled(true);

        btGravar.setEnabled(false);
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
    }//GEN-LAST:event_tbPedidoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btNovo;
    private javax.swing.JComboBox cbxPag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbTotalBobina;
    private javax.swing.JLabel lblTotalValor;
    private javax.swing.JTable tbPedido;
    private javax.swing.JTextField txtChequeA;
    private javax.swing.JTextField txtChequeB;
    private javax.swing.JTextField txtChequeC;
    private javax.swing.JFormattedTextField txtDataEntrega;
    private javax.swing.JFormattedTextField txtDataPedido;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtObs;
    private javax.swing.JTextField txtQuant;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
