/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package financeiro.gui;

import financeiro.DAO.BobinaDao;
import financeiro.DAO.CalculoNFDao;
import financeiro.conexao.Conexao;

import financeiro.model.CalculoNF;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ledilson
 */
public class EmissorCalculoNF extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioBoletoEmpresa
     */
    public EmissorCalculoNF() {
        initComponents();

        carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbCalculoNF = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNF = new javax.swing.JTable();
        txtTotalCarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFrete = new javax.swing.JTextField();
        txtCIpi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtComissao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCFrete = new javax.swing.JTextField();
        txtSomaComissao = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIPI = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        btEmitir = new javax.swing.JButton();
        lblFrete = new javax.swing.JLabel();
        lblIpi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTotalPagar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbCalculoNF.setBackground(new java.awt.Color(204, 204, 204));
        jbCalculoNF.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Exbir a Comissao");
        jbCalculoNF.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, 20));

        tbNF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Quanti", "Bobina", "Valor Unitario", "Peso Papel", "Valor", "Título 6", "Título 7", "Título 8"
            }
        ));
        jScrollPane1.setViewportView(tbNF);

        jbCalculoNF.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 890, 210));
        jbCalculoNF.add(txtTotalCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 170, 20));

        jLabel6.setText("Comissao  vai ser Digitado pelo Usuario");
        jbCalculoNF.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));
        jbCalculoNF.add(txtFrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, -1));
        jbCalculoNF.add(txtCIpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 70, -1));

        jLabel9.setText("Valor a pagar");
        jbCalculoNF.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 110, 20));
        jbCalculoNF.add(txtComissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, -1));

        jLabel10.setText("Frete digita vai exibir na tela");
        jbCalculoNF.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jLabel11.setText("Resultado T.Carga - Frete");
        jbCalculoNF.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, 20));
        jbCalculoNF.add(txtCFrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 70, -1));
        jbCalculoNF.add(txtSomaComissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 80, -1));

        jLabel12.setText("Resultado T.Carga + IPI");
        jbCalculoNF.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, 20));

        jLabel13.setText("IPI vai ser Digitado pelo Usuario");
        jbCalculoNF.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));
        jbCalculoNF.add(txtIPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, -1));

        jLabel14.setText("Digitado pelo usuarioT.Carga");
        jbCalculoNF.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 150, 20));

        btAdicionar.setText("Gravar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        jbCalculoNF.add(btAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 110, -1));

        btEmitir.setText("Emiti NF");
        jbCalculoNF.add(btEmitir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 120, -1));

        lblFrete.setText("0.00");
        jbCalculoNF.add(lblFrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 190, 40));

        lblIpi.setText("0.00");
        jbCalculoNF.add(lblIpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 210, 50));

        jLabel4.setText("jLabel4");
        jbCalculoNF.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        lblTotalPagar.setText("0.00");
        jbCalculoNF.add(lblTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 160, 70));

        jButton1.setText("Habilitar NS");
        jbCalculoNF.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbCalculoNF, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbCalculoNF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tbNF.getModel();
        modelo.setNumRows(0);

        try {

            Connection con = Conexao.getConnection();
            PreparedStatement pstm;
            ResultSet rs;

            pstm = con.prepareStatement("SELECT * FROM calculonf ;");
            rs = pstm.executeQuery();

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),});
            }
            Conexao.closeConnection(con, pstm, rs);

        } catch (Exception ErroSql) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar a tabela de dados: " + ErroSql, "ERRO", JOptionPane.ERROR_MESSAGE);

        }
    }
    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        CalculoNF n = new CalculoNF();
        CalculoNFDao dao = new CalculoNFDao();

        try {
            // Usuário digita o total da carga
            double totalCarga = Double.parseDouble(txtTotalCarga.getText());
            n.setTotalCarga(totalCarga);

            // Usuário digita o frete 
            double frete = Double.parseDouble(txtFrete.getText());
            n.setFrete(frete);

            // Usuário digita o Ipi
            double ipi = Double.parseDouble(txtIPI.getText());

            // Calcular CargaFrete: totalCarga - Frete.
            double cargaFrete = totalCarga - frete;

            // Armazenar o TotalCargaFrete 
            DecimalFormat dfFrete = new DecimalFormat("#.00");
            String valorFormatadoFrete = dfFrete.format(cargaFrete);
            lblFrete.setText("T. Carga Frete : " + valorFormatadoFrete);

            // Calcular CargaIpi: CargaFrete + IPI.
            double cargaIpi = cargaFrete + ipi;

            // Armazenar o TotalCargaIpi 
            DecimalFormat dfIpi = new DecimalFormat("#.00");
            String valorFormatadoIpi = dfIpi.format(cargaIpi);
            lblIpi.setText("T. Carga Ipi: " + valorFormatadoIpi);

            n.setImpostoIpi(ipi);

            // Usuário digita o Comissão
            double comissao = Double.parseDouble(txtComissao.getText());
            n.setComissao(comissao);

            // Calcular TotalApagar: CargaIpi - Comissão.
            double totalPagar = cargaIpi - comissao;

            // Armazenar o TotalApagar 
            DecimalFormat dfTotalPagar = new DecimalFormat("#.00");
            String valorFormatadoTotalPagar = dfTotalPagar.format(totalPagar);
            lblTotalPagar.setText("Total a Pagar: " + valorFormatadoTotalPagar);

            // Salvar no banco de dados
            n.setValorApagar(totalPagar);  // Certifique-se de ter um campo correspondente no objeto CalculoNF
            dao.adicionar(n);
            carregaTabela();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, digite valores numéricos válidos.", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmissorCalculoNF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmissorCalculoNF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmissorCalculoNF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmissorCalculoNF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmissorCalculoNF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btEmitir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jbCalculoNF;
    private javax.swing.JLabel lblFrete;
    private javax.swing.JLabel lblIpi;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JTable tbNF;
    private javax.swing.JTextField txtCFrete;
    private javax.swing.JTextField txtCIpi;
    private javax.swing.JTextField txtComissao;
    private javax.swing.JTextField txtFrete;
    private javax.swing.JTextField txtIPI;
    private javax.swing.JTextField txtSomaComissao;
    private javax.swing.JTextField txtTotalCarga;
    // End of variables declaration//GEN-END:variables
}
